package pl.appointmentbookingservice.appointment.domain;

public enum AppointmentBookingStatus {
  NEW,
  VAL_MEDICAL_PACKAGE_PENDING,
  VAL_MEDICAL_PACKAGE_REJECTED,
  VAL_MEDICAL_PACKAGE_APPROVED,
  APPOINTMENT_APPROVED,
  APPOINTMENT_BOOKING_PENDING,
  APPOINTMENT_REJECTED
}
